# Generated by Django 5.0 on 2024-03-06 16:42

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bits_id', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('location', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bits_id', models.CharField()),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=250)),
                ('user_mobile', models.CharField(max_length=30)),
                ('expense1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='trip3',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('people', models.IntegerField()),
                ('start_date1', models.DateField()),
                ('end_date1', models.DateField()),
                ('expense1', models.IntegerField()),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Trip_info',
            fields=[
                ('ty', models.IntegerField(primary_key=True, serialize=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trip3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='plans',
            fields=[
                ('id_plan', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trip3')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trip_info')),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('expense', models.IntegerField()),
                ('expense_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=250)),
                ('trip_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trip3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trip_info')),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('s_time', models.TimeField(max_length=200)),
                ('e_time', models.TimeField(max_length=200)),
                ('estimated', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.plans')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trip_info')),
            ],
        ),
    ]
