# Generated by Django 5.0 on 2024-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='followed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='followed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
