# Generated by Django 5.0 on 2024-03-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bits_id',
            field=models.CharField(default=123),
            preserve_default=False,
        ),
    ]
