# Generated by Django 5.0 on 2024-03-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_events_followed_alter_plans_followed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip3',
            name='people',
        ),
    ]
