# Generated by Django 5.0 on 2024-03-05 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip3',
            old_name='expense',
            new_name='expense1',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(default='hi', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='expense',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_id',
            field=models.IntegerField(default=152),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='trip_id1',
            field=models.ForeignKey(default=125, on_delete=django.db.models.deletion.CASCADE, to='blog.trip3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
