# Generated by Django 5.0 on 2024-03-05 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_trip_info_id_alter_trip_info_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trip_info'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.trip_info'),
        ),
    ]
