# Generated by Django 5.0 on 2024-03-05 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_events_owner_alter_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trip_info'),
        ),
    ]
