# Generated by Django 5.0 on 2024-03-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_expense_id_alter_expense_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='added_by',
        ),
    ]
